## Numpy Introduction

In [ ]:
# its is python library for scientic computation
# Numpy arrays are the main way to use numpy library
# Numpy works with multi dimantionas arrays
# it is really fastest as comapre to ordinary python list
# it is fastes becoz it has binding with c programming language

# 1-d array - vector
# 2-d array - matrix
# n-d array - tensor

### Create Numpy Arrays

In [3]:
import numpy as np

In [4]:
# 1-d Array/vector 
num =[1,2,3]
num = np.array(num)
print(num,"\n")
print(num.ndim,"\n")     #this is show this array as 1-d array --->([)
print(num.shape)         #this is show the shape of array row and column

[1 2 3] 

1 

(3,)


In [5]:
# 2-d array/Matrix 
num = [[1,2,3],[4,5,6]]
num = np.array(num)
print(num,"\n")
print(num.ndim,"\n")    #this is show this array as 2-d array --->([[)
print(num.shape)        #this is show the shape of array row and column

[[1 2 3]
 [4 5 6]] 

2 

(2, 3)


In [6]:
# n-d array/tensor/multidimantional array
num = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
num = np.array(num)
print(num,"\n")
print(num.ndim,"\n")    #this is show this array as 3-d array --->([[[)
print(num.shape)        #this is show the shape of array row and column

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

3 

(2, 2, 3)


### Create Numpy Arrays Using Functions

In [7]:
# Zeros,Ones,eye,diag,randint,rand,randin

In [8]:
import numpy as np

In [9]:
#Zeros Func as 1-d array
arr =np.zeros(3)
arr

array([0., 0., 0.])

In [10]:
#Zeros Func as 2-d array
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#Ones Func as 1-d array
arr =np.ones(3)
arr

array([1., 1., 1.])

In [12]:
#Ones Func as 2-d array
arr =np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#eye Func
arr =np.eye(4) #this is create dignal only 1 and another is 0
print(arr)
np.diag(arr) #this is used by show the diagnal are used in matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([1., 1., 1., 1.])

In [14]:
arr =np.eye(3,4) #this is create dignal only 1 and another is 0
print(arr)
np.diag(arr) #this is used by show the diagnal are used in matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


array([1., 1., 1.])

In [15]:
#diag Func
arr = np.diag([1,2,3,4]) #this is create Dignal as 1,2,3,4 and another is 0
print(arr)
np.diag(arr) #this is used by show the diagnal are used in matrix

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


array([1, 2, 3, 4])

In [16]:
# randint Func(Random Number Creater)
arr = np.random.randint(1,15,4) #To created random number 1 to 15 and  created 4 random numbers
arr

array([10, 14,  3,  7])

In [17]:
#Rand Func as 1-d array
arr = np.random.rand(2) #To created random number 0 to 1 and  created 4 random numbers
arr

array([0.05497612, 0.92651281])

In [18]:
#Rand Func as 2-d array
arr = np.random.rand(2,4) #To created random number 0 to 1 and  created 4 random numbers
arr

array([[0.9921641 , 0.28162111, 0.2842115 , 0.17936736],
       [0.87613117, 0.77348107, 0.17182843, 0.66856193]])

In [19]:
#Randn Func 
arr = np.random.randn(4) #To created random number 0 to 1,positive or nigative numbers and  created 4 random numbers
arr

array([-1.64489492,  0.43184733, -0.28402718, -0.81416113])

In [20]:
#Find the mean of rhis func 
arr = np.random.randn(15)
np.mean(arr)

0.2310654777047353

### Reshaping of Data

In [26]:
import numpy as np
arre = np.random.randint(1,50,20)
arre = arre.reshape(10,2)
arre

array([[24, 33],
       [17,  4],
       [16,  7],
       [ 1, 26],
       [20,  1],
       [21, 35],
       [23, 45],
       [11, 36],
       [45, 47],
       [22, 16]])

In [27]:
arre.ndim

2

### What is Negative 1 in reshape

In [39]:
arr = np.arange(1,111)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [41]:
arr.reshape(22,-1)  # -1 is assume numpy this number multiplication of 111

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

### Generate Same Random Number Every time 

In [47]:
np.random.seed(123)
arr = np.random.randint(1,20,10)
arr

array([14,  3,  3,  7, 18, 11,  2,  1, 18, 16])

In [48]:
arr.size

10

### Indexing and Slicing 1-d array

In [49]:
import numpy as np
arr = np.array([1,10,20,4,5])
arr

array([ 1, 10, 20,  4,  5])

In [50]:
#indexing
arr[2]

20

In [51]:
#Slicing
arr[0:3]

array([ 1, 10, 20])

In [52]:
arr[0:-3]

array([ 1, 10])

In [53]:
arr[0:-4:2]

array([1])

In [54]:
arr[::-1]

array([ 5,  4, 20, 10,  1])

### Indexing and Slicing 2-d array

### Create 2-d array

In [55]:
import numpy as np

In [57]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Indexing using double bracket Notation

In [58]:
matrix[1][1]

25

### Indexing using Single bracket Notation

In [59]:
matrix[1,1]

25

### Slicing using Single bracket Notation

In [60]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
matrix[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [64]:
matrix[1:3,:2]

array([[20, 25],
       [35, 40]])

In [65]:
np.random.seed(123)
matrix2 = np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [66]:
matrix2[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [68]:
matrix2[:3,2:]

array([[99, 18, 84],
       [98, 97, 48],
       [47, 97, 26]])

## View Vs Copy

In [86]:
arr = np.array([4,5,6,7,8,7])
arr

array([4, 5, 6, 7, 8, 7])

In [87]:
Sliced_arr = arr[2:5].copy()

In [88]:
Sliced_arr

array([6, 7, 8])

In [89]:
Sliced_arr[:] = 0

In [90]:
Sliced_arr

array([0, 0, 0])

In [91]:
arr

array([4, 5, 6, 7, 8, 7])

### Conditonal Selection

In [93]:
arr = np.arange(1,11)

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
dot =  arr>5

In [100]:
arr[dot]

array([ 6,  7,  8,  9, 10])

In [103]:
sot=arr%2==0

In [105]:
arr[sot]

array([ 2,  4,  6,  8, 10])

### Numpy Operation With Scaler

In [109]:
arr = np.array([1,2,3,4]).reshape(2,2)

In [110]:
arr**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [111]:
arr+3

array([[4, 5],
       [6, 7]])

In [112]:
arr-2


array([[-1,  0],
       [ 1,  2]])

In [113]:
arr/0

C:\Users\Omkar\AppData\Local\Temp/ipykernel_15464/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf],
       [inf, inf]])

### Operation On two or More Array

In [114]:
import numpy as np

In [126]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [127]:
arr1+arr2

array([ 6,  8, 10, 12])

In [128]:
arr1*arr1

array([ 1,  4,  9, 16])

In [129]:
arr1 = np.array([1,2,3,4]).reshape(2,2)
arr2 = np.array([5,6,7,8]).reshape(2,2)

In [130]:
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [138]:
arr3 = np.arange(1,11).reshape(5,2)

In [139]:
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Some More Functions Numpy

In [141]:
import numpy as np
arr4 = np.array([1,2,3,4])

In [142]:
np.min(arr4)

1

In [143]:
np.max(arr4)

4

In [144]:
np.argmin(arr4) #Give the position of minimum Number

0

In [145]:
np.argmax(arr4) #Give the position of maximum Number

3

In [1]:
np.linspace(1,15,5)

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [147]:
arr_s = np.array([1,2,3,4],dtype="bool")

In [148]:
arr_s

array([ True,  True,  True,  True])

### Numpy Axis

In [3]:
np.random.seed(123)
arr = np.random.randint(1,20,9).reshape(3,3)
arr

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [5]:
#Row = 1 And Column = 0 for Axis 
np.min(arr,axis=0)

array([2, 1, 3])

In [6]:
np.sum(arr,axis=1)

array([20, 36, 21])

In [7]:
np.cumsum(arr,axis=1)

array([[14, 17, 20],
       [ 7, 25, 36],
       [ 2,  3, 21]], dtype=int32)

### Shuffe and Unique Key

In [8]:
np.random.seed(123)
arr = np.random.randint(1,15,15)
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [11]:
np.random.shuffle(arr)


In [12]:
arr

array([ 1,  4, 10,  3, 10,  7, 12,  7,  2,  3, 14,  2,  2, 11, 13])

In [13]:
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [14]:
np.unique(arr).size

10

In [15]:
np.unique(arr,return_index=True,return_counts=True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 0,  8,  3,  1,  5,  2, 13,  6, 14, 10], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

### Horizontal And Vertical Stacking

In [1]:
np.random.seed(123)
matrix1 = np.random.randint(1,20,9).reshape(3,3)
matrix2 = np.random.randint(20,40,9).reshape(3,3)

In [2]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [3]:
matrix2 

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [4]:
# Horizontal Stacking
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [5]:
# Vertical Stacking
np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [8]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [9]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

### Numpy Array Vs Python list

In [1]:
%timeit 2+3

18.3 ns ± 0.725 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [10]:
%timeit [i**2 for i in range(1,11)]

5.37 µs ± 72.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
%%timeit
l =[]
for i in range(1,4):
    l.append(i**2)


1.97 µs ± 2.77 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
%timeit np.arange(1,11)**2

2.79 µs ± 40.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
